#! /bin/sh

sxhkd &

bspc monitor VGA-1 -d main term etc
bspc monitor LVDS-1 -d main term chat etc

bspc config border_width         0 
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a discord desktop='chat'
bspc rule -a telegram-desktop desktop='chat'

sh -e ~/.config/bspwm/polybar.sh
